### ISSUE TITLE
'NoneType' object is not callable when converting a graph

### ISSUE THREAD

**Issue by sirajmuhammad** [uTensor/utensor_cgen#45]
I am following the demo in [here](https://github.com/uTensor/uTensor/blob/master/docs/newProject.md) but when I try to generate the graph I get the following error:

```
Traceback (most recent call last):
  File "/home/siraj/.local/bin/utensor-cli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/siraj/.local/lib/python2.7/site-packages/utensor_cgen/cli.py", line 60, in convet_graph
    from utensor_cgen.code_generator import CodeGenerator
  File "/home/siraj/.local/lib/python2.7/site-packages/utensor_cgen/code_generator.py", line 11, in <module>
    from .operators import OperatorFactory
  File "/home/siraj/.local/lib/python2.7/site-packages/utensor_cgen/operators.py", line 9, in <module>
    from utensor_cgen.transformer.optimizer import RefCntOptimizer
  File "/home/siraj/.local/lib/python2.7/site-packages/utensor_cgen/transformer/__init__.py", line 2, in <module>
    from .ns_transformer import *
  File "/home/siraj/.local/lib/python2.7/site-packages/utensor_cgen/transformer/ns_transformer.py", line 11, in <module>
    from utensor_cgen.ir import OperationInfo, uTensorGraph
  File "/home/siraj/.local/lib/python2.7/site-packages/utensor_cgen/ir/__init__.py", line 1, in <module>
    from .base import *
  File "/home/siraj/.local/lib/python2.7/site-packages/utensor_cgen/ir/base.py", line 23, in <module>
    from .converter import AttrValueConverter, ConverterFactory
  File "/home/siraj/.local/lib/python2.7/site-packages/utensor_cgen/ir/converter.py", line 149, in <module>
    class GenericTensorShapeMixin(Converter):
  File "/home/siraj/.local/lib/python2.7/site-packages/utensor_cgen/ir/converter.py", line 151, in GenericTensorShapeMixin
    class GenericType(object):
  File "/home/siraj/.local/lib/python2.7/site-packages/utensor_cgen/ir/converter.py", line 154, in GenericType
    @list_view.validator
TypeError: 'NoneType' object is not callable
```
I had this error before the current version, when weights were generated as .idx files. Thought it would be solved but no luck.
Any idea of what might be the cause?

**Comment by dboyliao** [comment]
@sirajmuhammad 
Can you try it with Python3 or provide the `.pb` file which give rise to this issue?
